import type { Metadata } from "next";
import { Sriracha } from "next/font/google";
import "./globals.css";
import { MobileNav } from "@/components/mobil-nav";

const font = Sriracha({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Vita.AI - Elite AI Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
        <MobileNav />
      </body>
    </html>
  );
}
